services:
  nopcommerce-db:
    image: "postgres:latest"  
    container_name: nop-pg
    environment:
      POSTGRES_USER: nopuser
      POSTGRES_PASSWORD: noppassword
      POSTGRES_DB: nopcommerce
    ports:
      - "5432:5432"
    volumes:
      - nop-pg-data:/var/lib/postgresql/data
volumes:
  nop-pg-data: